### PR TITLE
#139 - Fix prev_sibling to actually return the previous sibling

### LINKED ISSUE #139: prev_sibling does not work as expected
A call to `syntax_node.prev_sibling()` returns actually the node two nodes before itself instead of the one before it.
I found out that `syntax_node.prev_sibling_or_token` works as expected and finds also the previous node.

To illustrate this issue, take the following tree of syntax nodes (only nodes, not tokens):
```
Root
    A
    B
    C
```
The calls to `prev_sibling` and `prev_sibling_or_token` report the following (per current node)
```
A
    prev_sibling=None
    prev_sibling_or_token=None
B
    prev_sibling=None
    prev_sibling_or_token=Some(Node(A))
C
    prev_sibling=Some(A)
    prev_sibling_or_token=Some(Node(B))
```

I found this by working with the rowan syntax trees in my rewrite of ( https://github.com/MalteJanz/ludtwig/tree/bachelor-thesis ) where I use rowan ( still in a very early state ). Parsing is done by the `GreenNodeBuilder` (abstracted away behind a sink / events). I have not yet found the time to produce a minimal reproducible example, so it would be nice if someone can confirm this behaviour in their rowan syntax trees or proof me wrong in my understanding of the function 🙈 .

I guess I already found the underlaying issue and will submit a PR shortly (offset by one error in [`src/cursor.rs` line 393](https://github.com/rust-analyzer/rowan/blob/188c607ff0c776d5c61fb58e0523ff110eb2c8c7/src/cursor.rs#L393)) 🙂.

### PR DESCRIPTION
**Pull request by MalteJanz**
closes #139

### CODE REVIEW

**Comment by matklad** [comment]
Can't believe no-one notice this before, excellent catch! Could you bump a patch version here to get a release https://github.com/rust-analyzer/rowan/blob/master/Cargo.toml#L3 ?

**Comment by matklad** [comment]
@bors r+

Thanks! Also, sorry that the testing situation with roawn is suboptimal... 

I feel like we should do some small language in this repo, to have proper tests...

**Comment by MalteJanz** [comment]
Done 👍 . A patch release would be nice. I was also quite suprised that my tree iteration doesn't work as expected when using the `prev_sibling` functions and that nobody encountered this before me😬.

By the way: you did an amazing job explaining how rowan works over here [syntax.md](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/syntax.md). I am still quite new to the whole parsing and syntax tree world and it was a good read😅.

**Comment by matklad** [comment]
@Veykril do we have any bors here?

**Comment by bjorn3** [comment]
Yes, but I believe it has been broken ever since rust-analyzer moved to the rust-lang org.

**Comment by Veykril** [comment]
Yep, bors is broken all across rust-analyzer since the move ...

**Pull request merged**
