### PR TITLE
Allow passing an iterable to `splice_children`

### PR DESCRIPTION
**Pull request by michaelvanstraten**
Should reduce two allocation when splicing children.

### CODE REVIEW

**Review by lnicola — APPROVED** [review]
Can you also bump the crate version number? I guess this isn't a breaking change.

**Comment by michaelvanstraten** [comment]
@lnicola, sorry for the delay, I've bumped the version number.

**Comment by milianw** [comment]
@Veykril can you also review and merge this? I assume bumping the crate version would also have been required for my PR, so getting this in here instead would solve this too.

**Comment by Veykril** [comment]
This needs a minor version bump, the signature change here could break callers

**Comment by michaelvanstraten** [comment]
> This needs a minor version bump, the signature change here could break callers

I don't see exactly how, since `I: IntoIterator<Item = SyntaxElement<L>>` is implemented for  `Vec<SyntaxElement>`.

**Comment by michaelvanstraten** [comment]
@Veykril is updated.

**Comment by milianw** [comment]
@Veykril ping? can this be merged now and a new release be tagged?

**Pull request merged**
