### PR TITLE
Move from TravisCI to GHA

### PR DESCRIPTION
**Pull request by CAD97**

### CODE REVIEW

**Comment by matklad** [comment]
LGTM!

**Comment by CAD97** [comment]
I... don't know why the action isn't triggering though... 😅

**Comment by CAD97** [comment]
It ran and passed when I pushed to master in my fork: https://github.com/cad97/rowan/actions/runs/155876775

So merging this as green, hopefully that will let GH pick up that the workflow exists. (If not, there's probably a setting you'll need to change.)

**Comment by CAD97** [comment]
Actions are running fine now that the workflow is on the target branch: https://github.com/rust-analyzer/rowan/actions/runs/155877867

**Comment by bjorn3** [comment]
Github actions isn't activated untill you push a workflow to the default branch.

**Pull request merged**
